import os

from flask import Flask, render_template, request, send_file
from io import BytesIO
from openpyxl import load_workbook
from supabase import create_client, Client

from convert_to_pdf import convert_excel_to_pdf
from mod_excel import add_suffix_to_filename, prepare_workbook_for_pdf, update_excel


app = Flask(__name__)

# Initialize Supabase Client using environment variables
SUPABASE_URL = os.environ.get("SUPABASE_URL")
SUPABASE_KEY = os.environ.get("SUPABASE_KEY")
supabase: Client = None

if SUPABASE_URL and SUPABASE_KEY:
    supabase = create_client(SUPABASE_URL, SUPABASE_KEY)

def _pdf_download_name(excel_filename: str) -> str:
    base, _ = os.path.splitext(excel_filename)
    return f"{base}_updated.pdf"

def upload_to_supabase_storage(file_bytes: bytes, destination_path: str) -> str:
    """Uploads bytes to Supabase storage bucket and returns the public download URL."""
    if not supabase:
        return ""
    
    bucket_name = "chit-files"
    # Upload file data
    supabase.storage.from_(bucket_name).upload(
        path=destination_path,
        file=file_bytes,
        file_options={"content-type": "application/octet-stream"}
    )
    # Retrieve public URL
    return supabase.storage.from_(bucket_name).get_public_url(destination_path)

def log_to_database(orig_name, format_type, orig_url, proc_url):
    """Inserts metadata logs into the PostgreSQL database."""
    if not supabase:
        return
    
    data = {
        "original_filename": orig_name,
        "output_format": format_type,
        "uploaded_file_url": orig_url,
        "processed_file_url": proc_url
    }
    supabase.table("file_logs").insert(data).execute()


@app.route("/", methods=["GET", "POST"])
def upload_file():
    if request.method == "POST":
        file = request.files["file"]
        output_format = request.form.get("output_format", "excel")

        if file.filename:
            if file.filename.endswith(".xlsx") or file.filename.endswith(".xls"):
                # Read original bytes before consumption by openpyxl
                original_file_bytes = file.read()
                
                # Load workbook using BytesIO
                my_workbook = load_workbook(filename=BytesIO(original_file_bytes))
                updated_workbook = update_excel(my_workbook)

                # Save updated workbook into memory buffer
                output_excel_buffer = BytesIO()
                updated_workbook.save(output_excel_buffer)
                processed_bytes = output_excel_buffer.getvalue()

                output_file = add_suffix_to_filename(file.filename, "_updated")
                
                # Unique folder structure in Cloud Storage based on timestamps to avoid name collisions
                import time
                timestamp_prefix = str(int(time.time()))
                orig_cloud_path = f"{timestamp_prefix}/original_{file.filename}"
                proc_cloud_path = f"{timestamp_prefix}/{output_file}"

                # Handle PDF layout branch if selected
                if output_format == "pdf":
                    try:
                        pdf_xlsx_bytes = prepare_workbook_for_pdf(updated_workbook)
                        processed_bytes = convert_excel_to_pdf(pdf_xlsx_bytes, output_file)
                        proc_cloud_path = f"{timestamp_prefix}/{_pdf_download_name(file.filename)}"
                    except ValueError as exc:
                        return render_template("index.html", error=str(exc))
                    except Exception:
                        return render_template(
                            "index.html",
                            error="PDF conversion failed. Please try again or download as Excel.",
                        )

                # --- Database & Storage Execution Loop ---
                if supabase:
                    try:
                        # 1. Upload both files concurrently into cloud storage buckets
                        uploaded_url = upload_to_supabase_storage(original_file_bytes, orig_cloud_path)
                        processed_url = upload_to_supabase_storage(processed_bytes, proc_cloud_path)
                        
                        # 2. Write structural telemetry metadata into PostgreSQL (timestamp is auto-generated by DB)
                        log_to_database(file.filename, output_format, uploaded_url, processed_url)
                    except Exception as db_err:
                        print(f"Cloud logging failed: {db_err}")
                        # Non-breaking check: compilation still serves file to client if DB fluctuates

                # Serve file stream straight back to browser
                mimetype = "application/pdf" if output_format == "pdf" else "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
                download_name = _pdf_download_name(file.filename) if output_format == "pdf" else output_file

                return send_file(
                    BytesIO(processed_bytes),
                    as_attachment=True,
                    mimetype=mimetype,
                    download_name=download_name,
                )

            return render_template(
                "index.html", error="Only Excel files (.xlsx, .xls) are allowed."
            )

        return render_template("index.html", error="Please choose a file to upload.")

    return render_template("index.html")


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8080)